name: Build and Test on ROS Noetic Ninjemys

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: "library/ros:noetic-ros-base"
      env:
        BUILD_TYPE: Release

    defaults:
      run: {shell: bash}

    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{GITHUB.WORKSPACE}}/src

    - name: Install APT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq python3-catkin-tools

    - name: Build catkin package
      working-directory: ${{GITHUB.WORKSPACE}}
      run: |
        catkin build --jobs 2 --cmake-args -DBUILD_TYPE=$BUILD_TYPE
