name: ROS Noetic Ninjemys

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore: ['README.md', 'LICENSE']
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore: ['README.md', 'LICENSE']

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: "library/ros:noetic-ros-base"
      env:
        BUILD_TYPE: Release

    defaults:
      run: {shell: bash}

    steps:
    - uses: actions/checkout@v4
      with:
        path: workspace/src

    - name: Install APT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq git python3-catkin-tools

    - name: Install ROS dependencies
      working-directory: ${{GITHUB.WORKSPACE}}/workspace
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        rosdep update
        rosdep install --from-paths src --ignore-src -y

    - name: Build catkin workspace
      working-directory: ${{GITHUB.WORKSPACE}}/workspace
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        catkin build --jobs $(nproc) --cmake-args -DBUILD_TYPE=$BUILD_TYPE

    - name: Run tests
      working-directory: ${{GITHUB.WORKSPACE}}/workspace
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        source ${{GITHUB.WORKSPACE}}/workspace/devel/setup.bash
        cd ${{GITHUB.WORKSPACE}}/workspace/build/catkin_template
        ctest -V
